
services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data_iot:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  server:
    build:
      context: raspberry
    env_file: .env
    # network_mode: host
    # volumes:
    #   - ./raspberry:/server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/tcp"
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    depends_on:
      - db

volumes:
  postgres_data_iot:
