
services:
  db:
    image: postgres:15.2-alpine
    env_file: ".env"
    volumes:
      - postgres_data_iot:/var/lib/postgresql/data
    restart: unless-stopped # Hace que el contenedor se reinicie a menos que se detenga manualmente 
    ports:
      - 5432:5432 # Puerto de postgres
  # Aqui el resto de servicios

volumes:
  postgres_data_iot:
