
services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data_iot:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  postgres_data_iot:
