
services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data_iot:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  server:
    build:
      context: raspberry
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./raspberry:/server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

volumes:
  postgres_data_iot:
